MACRO(VE_FIND_LIBRARY _lib _inc _deps _defs)
  STRING(TOUPPER ${_lib} _lib_upper)
  IF(NOT ${_lib_upper}_FOUND)
    IF(NOT DEFINED VENUS3D_ROOT AND DEFINED ENV{VENUS3D_PATH})
      SET(VENUS3D_ROOT $ENV{VENUS3D_PATH})
    ENDIF()
    IF(DEFINED VENUS3D_ROOT)
      GET_FILENAME_COMPONENT(VENUS3D_ROOT ${VENUS3D_ROOT} ABSOLUTE)
      SET(${_lib_upper}_FOUND true)
      SET(${_lib_upper}_INCLUDE_DIR ${VENUS3D_ROOT}/SDK/Include/${_lib})
      IF(NOT EXISTS ${${_lib_upper}_INCLUDE_DIR}/${_inc})
        SET(${_lib_upper}_FOUND false)
        UNSET(${_lib_upper}_INCLUDE_DIR)
      ENDIF()
      SET(${_lib_upper}_MULTI_LIB true)
      FILE(TO_CMAKE_PATH ${VENUS3D_ROOT}/SDK/Libraries ${_lib_upper}_LIBRARY)
    ENDIF()
    IF(${_lib_upper}_FOUND)
      UNSET(${_lib_upper}_DEPENDENTS)
      FOREACH(_dep ${_deps})
        LIST(APPEND ${_lib_upper}_DEPENDENTS ${_dep})
      ENDFOREACH()
      SET(${_lib_upper}_USER_DEFINITIONS "USE_${_lib_upper}")
      FOREACH(_def ${_defs})
        LIST(APPEND ${_lib_upper}_USER_DEFINITIONS ${_def})
      ENDFOREACH()
      MESSAGE(STATUS "[${_lib}] found in \"${${_lib_upper}_LIBRARY}\"")
    ELSE()
      MESSAGE(FATAL_ERROR "[${_lib}] not found")
    ENDIF()
  ENDIF()
ENDMACRO()
